# GitHub Actions workflow for building and testing a CMake project with SDL2 and SDL2_ttf
name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release, Debug]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install SDL2 dependencies on Linux
    - name: Install SDL2 dependencies (Linux only)
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-ttf-dev

    # Install SDL2 dependencies on Windows
    - name: Setup SDL2 (Windows only)
      if: runner.os == 'Windows'
      run: |
        # Download and extract precompiled SDL2 and SDL2_ttf binaries
        curl -LO https://www.libsdl.org/release/SDL2-devel-2.28.2-VC.zip
        curl -LO https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.20.1-VC.zip
        7z x SDL2-devel-2.28.2-VC.zip -oSDL2
        7z x SDL2_ttf-devel-2.20.1-VC.zip -oSDL2_ttf
        # Set environment variables for SDL2 and SDL2_ttf
        echo "SDL2_DIR=${{ github.workspace }}/SDL2" >> $GITHUB_ENV
        echo "SDL2_TTF_DIR=${{ github.workspace }}/SDL2_ttf" >> $GITHUB_ENV

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DSDL2_DIR=${{ env.SDL2_DIR }} 
        -DSDL2_TTF_DIR=${{ env.SDL2_TTF_DIR }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
